name: "JaCoCo Report"
description: "Publishes the JaCoCo report as a comment in the Pull Request"
inputs:
  paths:
    description: "Comma separated paths of the generated jacoco xml files"
    required: true
  token:
    description: "Github personal token to add commits to Pull Request"
    required: true
  min-coverage-overall:
    description: "The minimum code coverage that is required to pass for overall project"
    required: false
    default: "80"
  min-coverage-changed-files:
    description: "The minimum code coverage that is required to pass for changed files"
    required: false
    default: "80"
  title:
    description: "Optional title for the Pull Request comment"
    required: false
  update-comment:
    description: "Update the coverage report comment instead of creating new ones. Requires title to works properly."
    required: false
    default: "false"
  debug-mode:
    description: "Run the action in debug mode and get debug logs printed in console"
    required: false
    default: "true" # Todo change this to false!
  show-pages-links:
    description: "Render links to gh-pages sites showing code coverage"
    required: false
    default: "true" # Todo change this to false!
  #pages-url-template:
  #  description: "Base URL for code coverage hosting preview, file paths will be appended"
  #  required: false
  #  # TODO how to pass this in? Maybe combine with pr-preview as well?
  #  default: "https://${{ env.PAGES_URL }}/pr-preview/pr-${{ env.PR_NUMBER }}/"

# Outputs are unicode strings, maximum of 1MB each, 50MB total.
outputs:
  coverage-overall:
    description: "The overall coverage of the project"
  coverage-changed-files:
    description: "The total coverage of all changed files"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "percent"
  color: "green"
